# ========================= docker-compose.yml =========================
version: "3.9"

services:
  api:
    build: .
    image: yulleta/inference:latest      # GitHub Actions가 덮어씀
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    image: yulleta/inference:latest
    env_file: .env
    command: celery -A tasks.celery_app worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"          # 외부 공개가 필요 없으면 지워도 됨
 